-- Insert mock jobs
INSERT INTO jobs (
  id,
  title,
  company,
  company_logo,
  description,
  type,
  min_salary,
  max_salary,
  tags,
  requirements,
  contact,
  town_id,
  applicants,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'Senior Front End Developer',
  'Google Inc.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/2048px-Google_%22G%22_Logo.svg.png',
  'Join our team as a Senior Front End Developer and help build the next generation of web applications. You will be responsible for developing and maintaining complex web interfaces, optimizing performance, and mentoring junior developers.',
  'Full-time',
  80,
  150,
  ARRAY['React', 'TypeScript', 'Next.js', 'Frontend'],
  'Minimum 5 years of experience with modern JavaScript frameworks\nStrong understanding of web performance optimization\nExperience with TypeScript and React\nExcellent problem-solving skills',
  'careers@google.com',
  (SELECT id FROM towns ORDER BY RANDOM() LIMIT 1),
  2254,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Junior Front End Developer',
  'Apple Computer, Inc.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1667px-Apple_logo_black.svg.png',
  'Work alongside world-class designers and engineers to build beautiful and intuitive user interfaces for our web applications. You will help shape the future of our digital products.',
  'Full-time',
  50,
  100,
  ARRAY['JavaScript', 'CSS', 'HTML', 'Frontend'],
  'Bachelor''s degree in Computer Science or related field\nStrong foundation in HTML, CSS, and JavaScript\nKnowledge of modern frontend frameworks\nPassion for user experience',
  'jobs@apple.com',
  (SELECT id FROM towns ORDER BY RANDOM() LIMIT 1),
  1468,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Senior Backend Engineer',
  'Microsoft Corporation',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/2048px-Microsoft_logo.svg.png',
  'Join our cloud services team to build scalable and reliable backend systems. You will work on high-performance APIs and help architect solutions that serve millions of users.',
  'Remote',
  90,
  180,
  ARRAY['Python', 'AWS', 'Microservices', 'Backend'],
  'Extensive experience with Python and cloud services\nStrong background in distributed systems\nExperience with AWS or Azure\nExcellent communication skills',
  'careers@microsoft.com',
  (SELECT id FROM towns ORDER BY RANDOM() LIMIT 1),
  1876,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'DevOps Engineer',
  'Amazon Web Services',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/2560px-Amazon_Web_Services_Logo.svg.png',
  'Help us build and maintain our cloud infrastructure. You will work with cutting-edge technologies to automate deployments, improve system reliability, and optimize performance.',
  'Hybrid',
  70,
  140,
  ARRAY['DevOps', 'AWS', 'Docker', 'Kubernetes'],
  'Strong experience with AWS services\nProficiency with Docker and Kubernetes\nExperience with CI/CD pipelines\nStrong scripting skills',
  'aws-jobs@amazon.com',
  (SELECT id FROM towns ORDER BY RANDOM() LIMIT 1),
  1543,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'UI/UX Designer',
  'Meta',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/2560px-Meta_Platforms_Inc._logo.svg.png',
  'Join our design team to create beautiful and intuitive user interfaces for our social media platforms. You will work closely with product managers and engineers to deliver exceptional user experiences.',
  'Full-time',
  60,
  120,
  ARRAY['UI', 'UX', 'Figma', 'Design Systems'],
  'Strong portfolio demonstrating UI/UX skills\nExperience with Figma and design systems\nUnderstanding of user-centered design principles\nExcellent visual design skills',
  'design-jobs@meta.com',
  (SELECT id FROM towns ORDER BY RANDOM() LIMIT 1),
  892,
  NOW(),
  NOW()
);
